SECRET_KEY = "Starcraft"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "redsoft_docker"
DB_USER = "postgres"
DB_PASSWORD = "Starmall1977"
DOCKER_API_VERSION = "1.41"
DB_DRIVER="postgresql"
